//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IZhEasySnmp2", CallbackContract=typeof(WindowsFormsApplication1.ServiceReference1.IZhEasySnmp2Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IZhEasySnmp2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/SearchManage", ReplyAction="http://tempuri.org/IZhEasySnmp2/SearchManageResponse")]
        string SearchManage(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/UpadteInit", ReplyAction="http://tempuri.org/IZhEasySnmp2/UpadteInitResponse")]
        void UpadteInit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/GetCount", ReplyAction="http://tempuri.org/IZhEasySnmp2/GetCountResponse")]
        string GetCount(string Clx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/SearchSwitch", ReplyAction="http://tempuri.org/IZhEasySnmp2/SearchSwitchResponse")]
        string SearchSwitch(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/SearchTp", ReplyAction="http://tempuri.org/IZhEasySnmp2/SearchTpResponse")]
        string SearchTp(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/GetServerInfo", ReplyAction="http://tempuri.org/IZhEasySnmp2/GetServerInfoResponse")]
        string GetServerInfo(string Lx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/gets", ReplyAction="http://tempuri.org/IZhEasySnmp2/getsResponse")]
        string gets(string ip, string oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZhEasySnmp2/alter", ReplyAction="http://tempuri.org/IZhEasySnmp2/alterResponse")]
        string alter();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZhEasySnmp2Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IZhEasySnmp2/SendResult")]
        void SendResult(string json);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZhEasySnmp2Channel : WindowsFormsApplication1.ServiceReference1.IZhEasySnmp2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZhEasySnmp2Client : System.ServiceModel.DuplexClientBase<WindowsFormsApplication1.ServiceReference1.IZhEasySnmp2>, WindowsFormsApplication1.ServiceReference1.IZhEasySnmp2 {
        
        public ZhEasySnmp2Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ZhEasySnmp2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ZhEasySnmp2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ZhEasySnmp2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ZhEasySnmp2Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string SearchManage(string ip) {
            return base.Channel.SearchManage(ip);
        }
        
        public void UpadteInit() {
            base.Channel.UpadteInit();
        }
        
        public string GetCount(string Clx) {
            return base.Channel.GetCount(Clx);
        }
        
        public string SearchSwitch(string ip) {
            return base.Channel.SearchSwitch(ip);
        }
        
        public string SearchTp(string ip) {
            return base.Channel.SearchTp(ip);
        }
        
        public string GetServerInfo(string Lx) {
            return base.Channel.GetServerInfo(Lx);
        }
        
        public string gets(string ip, string oid) {
            return base.Channel.gets(ip, oid);
        }
        
        public string alter() {
            return base.Channel.alter();
        }
    }
}
